running job: 2
/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home-mscluster/erex/research_project/models/swav/main_swav.py", line 387, in <module>
    main()
  File "/home-mscluster/erex/research_project/models/swav/main_swav.py", line 133, in main
    init_distributed_mode(args)
  File "/home-mscluster/erex/research_project/models/swav/src/utils.py", line 60, in init_distributed_mode
    dist.init_process_group(
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 738, in _new_process_group_helper
    pg = ProcessGroupNCCL(prefix_store, rank, world_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 242823) of binary: /home-mscluster/erex/anaconda3/envs/swav/bin/python
Traceback (most recent call last):
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home-mscluster/erex/anaconda3/envs/swav/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main_swav.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-02-12_17:05:48
  host      : mscluster65.ms.wits.ac.za
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 242823)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
